# This pipeline runs in Azure Devops, but is triggered from Github. It could
# be used as a backup or complement to the Github actions, if we don't get a good integration going.

pool:
  demands:
    - sh
    - npm

trigger:
  - main

steps:
  - script: echo "The Azure pipeline has run!"
    displayName: 'A step in a pipeline triggered by Github.'

  # - checkout: self
  #   clean: true
  #   persistCredentials: true

  # - task: NodeTool@0
  #   displayName: "Use Node v14.14.0"
  #   inputs:
  #     versionSpec: 14.14.0

  # - script: npm install --global yarn@1.22.4
  #   displayName: "Install yarn"

  # - script: yarn install --frozen-lockfile
  #   displayName: "Install dependencies"

  # - script: yarn build
  #   displayName: "Build"

  # - script: yarn lint
  #   displayName: "Linting"

  # - script: yarn test
  #   displayName: "Testing"
